version: "3.8"
services:
  postgres:
    container_name: inclusion_connect_postgres
    image: "postgres:14"
    env_file:
      - docker/dev/keycloak/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/dev/postgres/psql_init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    ports:
      - 5433:5432
  smtp:
    container_name: inclusion_connect_smtp
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  keycloak:
    container_name: inclusion_connect_keycloak
    build:
      dockerfile: docker/dev/keycloak/Dockerfile
    volumes:
      - ./themes/inclusion-connect/:/opt/keycloak/themes/inclusion-connect/
    ports:
      - 8080:8080
    env_file:
      - docker/dev/keycloak/dev.env
volumes:
  postgres_data:
