version: "3.8"
services:
  keycloak:
    container_name: inclusion_connect_keycloak
    build:
      dockerfile: docker/dev/keycloak/Dockerfile
    volumes:
      - ./themes/inclusion-connect/:/opt/keycloak/themes/inclusion-connect/
    ports:
      - 8080:8080
    env_file:
      - docker/dev/keycloak/dev.env
